bases:
  - ../../base
commonLabels:
  environment: QA
patches:
# - path: patch-api-deplo.yaml
- target:
    kind: Deployment
    name: api-deployment
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: caddy
